import { Institusjon } from "./Institusjon";

export const INSTITUSJONER: Institusjon[] = [
    { id: 7414, navn: "Agderforskning" },
    { id: 1972, navn: "Akershus universitetssykehus HF" },
    { id: 255, navn: "Ansgar Teologiske Høgskole" },
    { id: 189, navn: "Arkitektur- og designhøgskolen i Oslo" },
    { id: 1526, navn: "Barratt Due musikkinstitutt" },
    { id: 2023, navn: "Betanien Hospital" },
    { id: 1620, navn: "Bjørknes høyskole" },
    { id: 1620, navn: "Chr. Michelsen Institute" },
    { id: 7416, navn: "Chr. Michelsen Institute" },
    { id: 7417, navn: "Christian Michelsen Research" },
    { id: 7475, navn: "CICERO Senter for klimaforskning" },
    { id: 190, navn: "Det teologiske Menighetsfakultet" },
    { id: 1990, navn: "Diakonhjemmet sykehus" },
    { id: 253, navn: "Dronning Mauds Minne Høgskole for barnehagelærerutdanning" },
    { id: 1901, navn: "Finnmarkssykehuset" },
    { id: 258, navn: "Fjellhaug Internasjonale Høgskole" },
    { id: 7502, navn: "Folkehelseinstituttet" },
    { id: 7425, navn: "Forskningsstiftelsen Fafo" },
    { id: 1627, navn: "Forsvaret" },
    { id: 7428, navn: "Forsvarets forskningsinstitutt" },
    { id: 7582, navn: "Frambu Senter for sjeldne funksjonshemninger" },
    { id: 7430, navn: "Fridtjof Nansens institutt" },
    { id: 158, navn: "Handelshøyskolen BI" },
    { id: 7431, navn: "Havforskningsinstituttet" },
    { id: 1905, navn: "Helgelandssykehuset HF" },
    { id: 1936, navn: "Helse Bergen HF - Haukeland universitetssykehus" },
    { id: 1932, navn: "Helse Fonna HF" },
    { id: 1935, navn: "Helse Førde HF" },
    { id: 1924, navn: "Helse Møre og Romsdal HF" },
    { id: 1900, navn: "Helse Nord RHF" },
    { id: 1918, navn: "Helse Nord-Trøndelag HF" },
    { id: 1938, navn: "Helse Stavanger HF - Stavanger universitetssjukehus" },
    { id: 203, navn: "Høgskolen i Bergen" },
    { id: 209, navn: "Høgskolen i Hedmark" },
    { id: 210, navn: "Høgskolen i Lillehammer" },
    { id: 211, navn: "Høgskolen i Molde - Vitenskapelig høgskole i logistikk" },
    { id: 215, navn: "Høgskolen i Oslo og Akershus" },
    { id: 222, navn: "Høgskolen i Sørøst-Norge" },
    { id: 224, navn: "Høgskolen i Østfold" },
    { id: 218, navn: "Høgskolen Stord/Haugesund" },
    { id: 1622, navn: "Høgskulen for landbruk og bygdeutvikling" },
    { id: 216, navn: "Høgskulen i Sogn og Fjordane" },
    { id: 223, navn: "Høgskulen i Volda" },
    { id: 232, navn: "Høyskolen Diakonova" },
    { id: 1624, navn: "Høyskolen for Ledelse og Teologi" },
    { id: 1615, navn: "Høyskolen Kristiania" },
    { id: 7492, navn: "Institutt for energiteknikk" },
    { id: 7437, navn: "Institutt for samfunnsforskning" },
    { id: 7473, navn: "IRIS - International Research Institute of Stavanger" },
    { id: 5737, navn: "Kreftregisteret - Institutt for populasjonsbasert kreftforskning" },
    { id: 7576, navn: "Kriminalomsorgens høgskole og utdanningssenter KRUS" },
    { id: 260, navn: "Kunsthøgskolen i Oslo" },
    { id: 2031, navn: "LHL-klinikkene" },
    { id: 230, navn: "Lovisenberg diakonale høgskole" },
    { id: 1992, navn: "Lovisenberg Diakonale Sykehus" },
    { id: 7566, navn: "MARINTEK" },
    { id: 1993, navn: "Martina Hansens Hospital" },
    { id: 7419, navn: "Meteorologisk institutt" }, 
    { id: 7602, navn: "Modum Bad" },
    { id: 7443, navn: "Møreforsking" },
    { id: 7444, navn: "Nansen Senter for Miljø og Fjernmåling" },
    { id: 1305, navn: "Nasjonalmuseet for kunst, arkitektur og design" },
    { id: 7527, navn: "Nasjonalt institutt for ernærings- og sjømatforskning" },
    { id: 6077, navn: "Nasjonalt kunnskapssenter om vold og traumatisk stress" },
    { id: 7463, navn: "NIFU Nordisk institutt for studier av innovasjon, forskning og utdanning" },
    { id: 7460, navn: "NILU - Norsk institutt for luftforskning" },
    { id: 7520, navn: "NIOM - Nordisk Institutt for Odontologiske Materialer" },
    { id: 7543, navn: "NOFIMA" },
    { id: 204, navn: "Nord Universitet" },
    { id: 7446, navn: "Nordlandsforskning" },
    { id: 1904, navn: "Nordlandssykehuset HF" },
    { id: 1506, navn: "Norges Dansehøyskole" },
    { id: 7452, navn: "Norges Geotekniske Institutt" },
    { id: 150, navn: "Norges idrettshøgskole" },
    { id: 192, navn: "Norges miljø- og biovitenskapelige universitet" },
    { id: 178, navn: "Norges musikkhøgskole" },
    { id: 194, navn: "Norges teknisk-naturvitenskapelige universitet" },
    { id: 7453, navn: "NORSAR" },
    { id: 7677, navn: "Norsk institutt for bioøkonomi" },
    { id: 7530, navn: "Norsk institutt for kulturminneforskning" },
    { id: 7511, navn: "Norsk institutt for naturforskning" },
    { id: 7464, navn: "Norsk institutt for vannforskning" },
    { id: 7467, navn: "Norsk Regnesentral" },
    { id: 7501, navn: "Norsk senter for bygdeforskning" },
    { id: 7471, navn: "Norsk Utenrikspolitisk Institutt" },
    { id: 6228, navn: "Northern Research Institute Narvik AS" },
    { id: 6002, navn: "Norut Northern Research Institute AS" },
    { id: 7403, navn: "NTNU Samfunnsforskning AS" },
    { id: 2012, navn: "Oslo universitetssykehus HF" },
    { id: 233, navn: "Politihøgskolen" },
    { id: 7435, navn: "PRIO - Institutt for fredsforskning" },
    { id: 1937, navn: "Private ideelle i Helse Vest" },
    { id: 7539, navn: "RBUP Øst og Sør" }, 
    { id: 2003, navn: "Revmatismesykehuset AS" },
    { id: 7572, navn: "Samfunns- og næringslivsforskning AS" },
    { id: 231, navn: "Sámi allaskuvla/Samisk høgskole" },
    { id: 7548, navn: "SINTEF Energi AS" },
    { id: 7569, navn: "SINTEF Fiskeri og havbruk AS" },
    { id: 7571, navn: "SINTEF Petroleum AS" },
    { id: 7630, navn: "SINTEF Raufoss Manufacturing AS" },
    { id: 1933, navn: "Sjukehusapoteka Vest HF" },
    { id: 1920, navn: "St. Olavs Hospital HF" },
    { id: 7476, navn: "Statens arbeidsmiljøinstitutt" },
    { id: 1525, navn: "Steinerhøyskolen" },
    { id: 7495, navn: "Stiftelsen Frischsenteret for samfunnsøkonomisk forskning" },
    { id: 7401, navn: "Stiftelsen SINTEF" },
    { id: 1982, navn: "Sunnaas sykehus HF" }, 
    { id: 1906, navn: "Sykehusapotek Nord HF" },
    { id: 1919, navn: "Sykehusapotekene i Midt-Norge HF" },
    { id: 1986, navn: "Sykehusapotekene i Sør-Øst RHF" },
    { id: 1958, navn: "Sykehuset i Vestfold HF" }, 
    { id: 1991, navn: "Sykehuset Innlandet HF" },
    { id: 1959, navn: "Sykehuset Telemark HF" },
    { id: 1983, navn: "Sykehuset Østfold HF" },
    { id: 1965, navn: "Sørlandet sykehus HF" }, 
    { id: 7556, navn: "Teknova AS" }, 
    { id: 7480, navn: "Telemarksforsking" }, 
    { id: 7479, navn: "Tel-Tek" },
    { id: 7482, navn: "Transportøkonomisk institutt" },
    { id: 7448, navn: "Trøndelag Forskning og Utvikling" },
    { id: 186, navn: "UiT - Norges arktiske universitet" }, 
    { id: 305, navn: "UNI Research" },
    { id: 7600, navn: "UNI Research Polytec AS" },
    { id: 201, navn: "Universitetet i Agder" },
    { id: 184, navn: "Universitetet i Bergen" },
    { id: 185, navn: "Universitetet i Oslo" },
    { id: 217, navn: "Universitetet i Stavanger" }, 
    { id: 195, navn: "Universitetssenteret på Svalbard" }, 
    { id: 1616, navn: "Universitetsstudiene på Kjeller" },
    { id: 1902, navn: "Universitetssykehuset Nord-Norge HF" }, 
    { id: 6281, navn: "Valnesfjord Helsesportssenter" },
    { id: 7484, navn: "Vestlandsforsking" },
    { id: 2017, navn: "Vestre Viken HF" },
    { id: 7497, navn: "Veterinærinstituttet" },
    { id: 251, navn: "VID vitenskapelige høgskole" },
    { id: 1655, navn: "Westerdals Oslo School of Arts, Communication and Technology" },
    { id: 7407, navn: "Østfoldforskning AS" },
    { id: 7486, navn: "Østlandsforskning AS" }
]